-- Massachusetts saturation: seed the universal RSS scraper with city/town
-- and regional news feeds, government press releases, and trade-specific
-- syndication. Each feed is filtered against its keywords[] array before
-- being inserted as a marketplace lead and routed through curation.
--
-- Coverage strategy:
--   1. Patch.com town feeds (broad MA municipal news, mentions permits + builds)
--   2. Wicked Local / Gannett town pages
--   3. Major regional newspapers (Globe, Worcester T&G, Cape Cod Times, etc.)
--   4. State + agency press releases (DCR, MassDEP, mass.gov housing)
--   5. Construction-specific RSS where available
--
-- Safe to re-run — rss_sources.url has UNIQUE constraint, ON CONFLICT DO NOTHING.

INSERT INTO public.rss_sources (name, url, keywords, city, ai_score, price_cents)
VALUES
  -- ── Patch.com town feeds (residential + permit-adjacent news) ────────
  ('Patch · Boston',          'https://patch.com/massachusetts/boston/feed',          ARRAY['permit','renovation','remodel','construction','homeowner','built','contractor','addition','deck','roof','electrical','plumbing','hvac','kitchen','bathroom'], 'Boston',          40, 800),
  ('Patch · Cambridge',       'https://patch.com/massachusetts/cambridge/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Cambridge',       40, 800),
  ('Patch · Somerville',      'https://patch.com/massachusetts/somerville/feed',      ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Somerville',      40, 800),
  ('Patch · Brookline',       'https://patch.com/massachusetts/brookline/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Brookline',       40, 800),
  ('Patch · Newton',          'https://patch.com/massachusetts/newton/feed',          ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Newton',          40, 800),
  ('Patch · Quincy',          'https://patch.com/massachusetts/quincy/feed',          ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Quincy',          40, 800),
  ('Patch · Worcester',       'https://patch.com/massachusetts/worcester/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Worcester',       40, 800),
  ('Patch · Springfield',     'https://patch.com/massachusetts/springfield/feed',     ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Springfield',     40, 800),
  ('Patch · Lowell',          'https://patch.com/massachusetts/lowell/feed',          ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Lowell',          40, 800),
  ('Patch · Lawrence',        'https://patch.com/massachusetts/lawrence/feed',        ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Lawrence',        40, 800),
  ('Patch · Brockton',        'https://patch.com/massachusetts/brockton/feed',        ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Brockton',        40, 800),
  ('Patch · Lynn',            'https://patch.com/massachusetts/lynn/feed',            ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Lynn',            40, 800),
  ('Patch · Fall River',      'https://patch.com/massachusetts/fallriver/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Fall River',      40, 800),
  ('Patch · New Bedford',     'https://patch.com/massachusetts/newbedford/feed',      ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'New Bedford',     40, 800),
  ('Patch · Framingham',      'https://patch.com/massachusetts/framingham/feed',      ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Framingham',      40, 800),
  ('Patch · Haverhill',       'https://patch.com/massachusetts/haverhill/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Haverhill',       40, 800),
  ('Patch · Waltham',         'https://patch.com/massachusetts/waltham/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Waltham',         40, 800),
  ('Patch · Malden',          'https://patch.com/massachusetts/malden/feed',          ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Malden',          40, 800),
  ('Patch · Medford',         'https://patch.com/massachusetts/medford/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Medford',         40, 800),
  ('Patch · Taunton',         'https://patch.com/massachusetts/taunton/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Taunton',         40, 800),
  ('Patch · Chicopee',        'https://patch.com/massachusetts/chicopee/feed',        ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Chicopee',        40, 800),
  ('Patch · Weymouth',        'https://patch.com/massachusetts/weymouth/feed',        ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Weymouth',        40, 800),
  ('Patch · Revere',          'https://patch.com/massachusetts/revere/feed',          ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Revere',          40, 800),
  ('Patch · Peabody',         'https://patch.com/massachusetts/peabody/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Peabody',         40, 800),
  ('Patch · Methuen',         'https://patch.com/massachusetts/methuen/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Methuen',         40, 800),
  ('Patch · Barnstable',      'https://patch.com/massachusetts/barnstable/feed',      ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Barnstable',      40, 800),
  ('Patch · Pittsfield',      'https://patch.com/massachusetts/pittsfield/feed',      ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Pittsfield',      40, 800),
  ('Patch · Attleboro',       'https://patch.com/massachusetts/attleboro/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Attleboro',       40, 800),
  ('Patch · Salem',           'https://patch.com/massachusetts/salem/feed',           ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Salem',           40, 800),
  ('Patch · Beverly',         'https://patch.com/massachusetts/beverly/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Beverly',         40, 800),
  ('Patch · Gloucester',      'https://patch.com/massachusetts/gloucester/feed',      ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Gloucester',      40, 800),
  ('Patch · Andover',         'https://patch.com/massachusetts/andover/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Andover',         40, 800),
  ('Patch · North Andover',   'https://patch.com/massachusetts/northandover/feed',    ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'North Andover',   40, 800),
  ('Patch · Belmont',         'https://patch.com/massachusetts/belmont/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Belmont',         40, 800),
  ('Patch · Arlington',       'https://patch.com/massachusetts/arlington/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Arlington',       40, 800),
  ('Patch · Watertown',       'https://patch.com/massachusetts/watertown/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Watertown',       40, 800),
  ('Patch · Wellesley',       'https://patch.com/massachusetts/wellesley/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Wellesley',       40, 800),
  ('Patch · Needham',         'https://patch.com/massachusetts/needham/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Needham',         40, 800),
  ('Patch · Dedham',          'https://patch.com/massachusetts/dedham/feed',          ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Dedham',          40, 800),
  ('Patch · Milton',          'https://patch.com/massachusetts/milton/feed',          ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Milton',          40, 800),
  ('Patch · Braintree',       'https://patch.com/massachusetts/braintree/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Braintree',       40, 800),
  ('Patch · Hingham',         'https://patch.com/massachusetts/hingham/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Hingham',         40, 800),
  ('Patch · Plymouth',        'https://patch.com/massachusetts/plymouth/feed',        ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Plymouth',        40, 800),
  ('Patch · Hyannis',         'https://patch.com/massachusetts/hyannis/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Barnstable',      40, 800),
  ('Patch · Falmouth',        'https://patch.com/massachusetts/falmouth/feed',        ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Falmouth',        40, 800),
  ('Patch · Acton',           'https://patch.com/massachusetts/acton/feed',           ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Acton',           40, 800),
  ('Patch · Lexington',       'https://patch.com/massachusetts/lexington/feed',       ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Lexington',       40, 800),
  ('Patch · Concord',         'https://patch.com/massachusetts/concord/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Concord',         40, 800),
  ('Patch · Burlington',      'https://patch.com/massachusetts/burlington/feed',      ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Burlington',      40, 800),
  ('Patch · Woburn',          'https://patch.com/massachusetts/woburn/feed',          ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Woburn',          40, 800),
  ('Patch · Winchester',      'https://patch.com/massachusetts/winchester/feed',      ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Winchester',      40, 800),
  ('Patch · Stoneham',        'https://patch.com/massachusetts/stoneham/feed',        ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Stoneham',        40, 800),
  ('Patch · Northampton',     'https://patch.com/massachusetts/northampton/feed',     ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Northampton',     40, 800),
  ('Patch · Amherst',         'https://patch.com/massachusetts/amherst/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Amherst',         40, 800),
  ('Patch · Holyoke',         'https://patch.com/massachusetts/holyoke/feed',         ARRAY['permit','renovation','remodel','construction','contractor','addition','deck','roof','kitchen','bathroom'], 'Holyoke',         40, 800),

  -- ── Regional newspapers (MA) ─────────────────────────────────────────
  ('Boston Globe · Real Estate',
   'https://www.bostonglobe.com/rss/sections/business/real-estate',
   ARRAY['home','homeowner','permit','renovation','construction','remodel','property','listing','market'],
   'Boston', 45, 1200),
  ('Worcester Telegram & Gazette',
   'https://www.telegram.com/feeds/local',
   ARRAY['permit','renovation','remodel','construction','contractor','addition','property'],
   'Worcester', 40, 1000),
  ('Cape Cod Times',
   'https://www.capecodtimes.com/feeds/local',
   ARRAY['permit','renovation','remodel','construction','contractor','addition','property'],
   'Barnstable', 40, 1000),
  ('MetroWest Daily News',
   'https://www.metrowestdailynews.com/feeds/local',
   ARRAY['permit','renovation','remodel','construction','contractor','addition','property'],
   'Framingham', 40, 1000),
  ('Eagle-Tribune (Lawrence + Merrimack)',
   'https://www.eagletribune.com/search/?f=rss&t=article&c=news&l=50&s=start_time&sd=desc',
   ARRAY['permit','renovation','remodel','construction','contractor','addition','property'],
   'Lawrence', 40, 1000),
  ('Berkshire Eagle',
   'https://www.berkshireeagle.com/feeds/local',
   ARRAY['permit','renovation','remodel','construction','contractor','addition','property'],
   'Pittsfield', 40, 1000),
  ('The Salem News',
   'https://www.salemnews.com/search/?f=rss&t=article&c=news&l=50&s=start_time&sd=desc',
   ARRAY['permit','renovation','remodel','construction','contractor','addition','property'],
   'Salem', 40, 1000),
  ('The Standard-Times (New Bedford)',
   'https://www.southcoasttoday.com/feeds/local',
   ARRAY['permit','renovation','remodel','construction','contractor','addition','property'],
   'New Bedford', 40, 1000),
  ('The Herald News (Fall River)',
   'https://www.heraldnews.com/feeds/local',
   ARRAY['permit','renovation','remodel','construction','contractor','addition','property'],
   'Fall River', 40, 1000),
  ('Daily Hampshire Gazette',
   'https://www.gazettenet.com/feed',
   ARRAY['permit','renovation','remodel','construction','contractor','addition','property'],
   'Northampton', 40, 1000),

  -- ── MA state + agency RSS ────────────────────────────────────────────
  ('Mass.gov press releases',
   'https://www.mass.gov/news.rss',
   ARRAY['housing','construction','grant','renovation','rebuild','infrastructure','permit','building'],
   NULL, 45, 1500),
  ('MassDEP environmental news',
   'https://www.mass.gov/orgs/massachusetts-department-of-environmental-protection/news.rss',
   ARRAY['permit','construction','demolition','remediation','asbestos','cleanup'],
   NULL, 50, 1500),
  ('MA DCR press releases',
   'https://www.mass.gov/orgs/department-of-conservation-recreation/news.rss',
   ARRAY['construction','renovation','rfp','contract','project','rebuild'],
   NULL, 45, 1200),
  ('MA Operational Services Division (state contracts)',
   'https://www.mass.gov/orgs/operational-services-division/news.rss',
   ARRAY['rfp','contract','bid','procurement','construction','renovation','repair'],
   NULL, 50, 1500),

  -- ── Construction-trade RSS ───────────────────────────────────────────
  ('Builder Magazine',
   'https://www.builderonline.com/rss',
   ARRAY['kitchen','bathroom','remodel','renovation','addition','contractor','deck','roof','electrical','plumbing','hvac'],
   NULL, 30, 500),
  ('Remodeling Magazine',
   'https://www.remodelingmag.com/rss',
   ARRAY['kitchen','bathroom','remodel','renovation','addition','contractor','deck','roof','electrical','plumbing','hvac'],
   NULL, 30, 500),
  ('Pro Remodeler',
   'https://www.proremodeler.com/rss',
   ARRAY['kitchen','bathroom','remodel','renovation','addition','deck','roof','electrical','plumbing','hvac'],
   NULL, 30, 500)
ON CONFLICT (url) DO NOTHING;
